#+TITLE: Cookiecutter CI CWI

A Cookiecutter template for starting your Python projects at CI CWI.

This template lets you easily set up a Python package for your own projects.
It automatically creates a directory tree with sensible locations for your
code, documentation and tests, and directly makes a number of useful tools
available to more conveniently install, document and eventually publish your
project.

- GitHub repository: TODO
- Documentation: TODO
- License: BSD

* Features

- Documentation with Sphinx
- Conda packaging

* Quickstart
Install the latest Cookiecutter if you haven't installed it yet (this requires
Cookiecutter 1.4.0 or higher)::

#+BEGIN_SRC bash
pip install -U cookiecutter
#+END_SRC


Generate a Python package project::

#+BEGIN_SRC bash
cookiecutter https://github.com/cicwi/cookiecutter-cicwi.git
#+END_SRC

Then:
1. Answer the questions that cookiecutter asks, for instance
   #+BEGIN_EXAMPLE
   $ cookiecutter gh:cicwi/cookiecutter-cicwi
   You've downloaded /ufs/hendriks/.cookiecutters/cookiecutter-cicwi before. Is it okay to delete and re-download it? [yes]: yes
   full_name [Your Name]: Allard Hendriksen
   email [example@example.com]: allard.hendriksen@cwi.nl
   github_username [cicwi]: ahendriksen
   project_name [Human readable project name]: Cone Balls
   project_slug [cone_balls]:
   project_short_description [Python CI CWI boilerplate package.]: A package for bubble phantom generation using a cone beam CT geometry.
   version [0.1.0]:
   use_pytest [n]:
   Select open_source_license:
   1 - GNU General Public License v3
   2 - Apache Software License 2.0
   3 - Not open source
   Choose from 1, 2, 3 [1]: 1
   #+END_EXAMPLE
   Note that =slug= means a project name without spaces that is usable
   as directory name and GitHub project name.
2. =cd new-project=
3. =git init=
4. Install development requirements
   1. =make install_dev=
5. Install requirements
   1. =make install=
6. Update README
7. Write software
8. Keep changelog
9. Update documentation
   1. make docs
10. Commit code
11. Update version in =VERSION= file
12. Push to github
13. Create release on GitHub
14. Create GitHub pages documentation

* Make commands

The project comes with a default Makefile. The Makefile has a
reasonable number of built-in commands.

** Development requirements
Download and install development requirements into your current conda
environment with
#+BEGIN_SRC bash
make install_dev
#+END_SRC

*** TODO this installs

** Install requirements
Download and install your project requirements into your current conda
environment with
#+BEGIN_SRC bash
make install
#+END_SRC

*** TODO this installs

** Update the documentation.
Update your documentation with
#+BEGIN_SRC bash
make docs
#+END_SRC
** Code formatting
Automatically reformat the code of your project to a common format
with
#+BEGIN_SRC bash
make style
#+END_SRC
** Build conda package
The command
#+BEGIN_SRC bash
make conda_package
#+END_SRC
builds a conda package, which you can share on https://anaconda.org/.
* Authors and contributors
- Allard Hendriksen
- Jan-Willem Buurlage

* How to contribute
Contributions are always welcome. Please submit pull requests against
the ~develop~ branch.

If you have any issues, questions, or remarks, then please open an
issue on GitHub.

* License
This project is licensed under the BSD License - see the =LICENSE= file for details
